"""Estimate the signed optical common-noise mode from two-spin phase samples.

Input CSV values are phase increments in radians generated by the exact optical
block.  The deterministic mean is removed before the covariance is calculated.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

import numpy as np


def load_phase_columns(path: Path, columns: tuple[str, str]) -> np.ndarray:
    rows: list[tuple[float, float]] = []
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        missing = [name for name in columns if name not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(f"CSV is missing columns: {missing}")
        for line_number, row in enumerate(reader, start=2):
            try:
                values = (float(row[columns[0]]), float(row[columns[1]]))
            except (TypeError, ValueError) as exc:
                raise ValueError(f"Invalid phase value on CSV line {line_number}") from exc
            if not np.all(np.isfinite(values)):
                raise ValueError(f"Non-finite phase value on CSV line {line_number}")
            rows.append(values)
    if len(rows) < 3:
        raise ValueError("At least three phase samples are required")
    return np.asarray(rows, dtype=float)


def analyze_optical_mode(samples: np.ndarray, labels: tuple[str, str]) -> dict:
    samples = np.asarray(samples, dtype=float)
    if samples.ndim != 2 or samples.shape[1] != 2 or samples.shape[0] < 3:
        raise ValueError("samples must have shape (shots, 2), with at least three shots")

    mean = np.mean(samples, axis=0)
    centered = samples - mean
    covariance = np.cov(centered, rowvar=False, ddof=1)
    eigenvalues, eigenvectors = np.linalg.eigh(covariance)
    order = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[order]
    eigenvectors = eigenvectors[:, order]

    principal = eigenvectors[:, 0].copy()
    dominant_index = int(np.argmax(np.abs(principal)))
    if principal[dominant_index] < 0:
        principal *= -1.0

    physical_order = np.argsort(np.abs(principal))[::-1]
    ordered_mode = principal[physical_order].copy()
    ordered_labels = [labels[int(i)] for i in physical_order]
    if ordered_mode[0] < 0:
        ordered_mode *= -1.0

    ratio = float(ordered_mode[1] / ordered_mode[0])
    if abs(ratio) > 1.0 + 1e-12:
        raise RuntimeError("Internal ordering error: |g2/g1| exceeds one")
    ratio = float(np.clip(ratio, -1.0, 1.0))
    a = math.sqrt((1.0 - ratio) / 2.0)
    b = math.sqrt((1.0 + ratio) / 2.0)

    denominator = math.sqrt(max(covariance[0, 0] * covariance[1, 1], 0.0))
    correlation = float(covariance[0, 1] / denominator) if denominator > 0 else float("nan")
    total_variance = float(np.sum(eigenvalues))
    common_mode_fraction = float(eigenvalues[0] / total_variance) if total_variance > 0 else float("nan")

    return {
        "phase_columns": list(labels),
        "shots": int(samples.shape[0]),
        "mean_phase_rad": mean.tolist(),
        "covariance_rad2": covariance.tolist(),
        "correlation": correlation,
        "eigenvalues_rad2": eigenvalues.tolist(),
        "common_mode_fraction": common_mode_fraction,
        "principal_mode_in_input_order": principal.tolist(),
        "code_spin_order": ordered_labels,
        "ordered_signed_mode": ordered_mode.tolist(),
        "signed_ratio_g2_over_g1": ratio,
        "code_coefficients": {"a": a, "b": b},
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv_path", type=Path)
    parser.add_argument("--columns", nargs=2, required=True, metavar=("PHI1", "PHI2"))
    parser.add_argument("--output", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    columns = (str(args.columns[0]), str(args.columns[1]))
    samples = load_phase_columns(args.csv_path, columns)
    result = analyze_optical_mode(samples, columns)
    rendered = json.dumps(result, indent=2, allow_nan=False)
    if args.output is None:
        print(rendered)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered + "\n", encoding="utf-8")
        print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
