"""Five-level NV-center + two 13C Bell-state QEC simulation.

This script uses DQP rows of the form (-A_parallel, A_perp) in kHz,
selects two nuclear spins, embeds them in a five-level NV Lindblad model,
and compares Bell-state fidelity with and without the n=2
common-fluctuator dephasing recovery protocol of Layden, Chen, and
Cappellaro.

Two QEC timing modes are generated by default:

1. Periodic recovery at a realistic configurable cadence
   (--recovery-interval-us, default 10 us).  The recovery channel is still
   modeled as ideal and instantaneous; the longer cadence is a timing proxy
   for a recovery that itself requires several one- and two-qubit gates.

2. A single-recovery trace with exactly one recovery operation at
   --single-recovery-time-us (default: half of --time-us).  A vertical line
   is drawn at that recovery time.

Units:
    time: microseconds
    Hamiltonian angular frequencies: rad / microsecond
    input A values: kHz in dqpspins.json, converted to MHz then angular units
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import scipy.linalg as la

DEFAULT_DQP_SPINS = [
    [7.880658979484622, 35.18660952634182],
    [224.2991967686721, 199.07207268788648],
    [50.10705093918639, 108.7263051655999],
    [17.11980460341208, 19.548809690807488],
    [5.928129614204922, 21.140094092827646],
    [-4.919015344947458, 38.25005007258501],
]


@dataclass(frozen=True)
class DQPSpin:
    """One DQP spin row stored as (-A_parallel, A_perp) in kHz."""

    index: int
    minus_A_par_kHz: float
    A_perp_kHz: float

    @property
    def A_par_MHz(self) -> float:
        return -self.minus_A_par_kHz / 1000.0

    @property
    def A_perp_MHz(self) -> float:
        return self.A_perp_kHz / 1000.0

    @property
    def g_MHz(self) -> float:
        # The n=2 efficient code uses H_E = g1 Z1 + g2 Z2.  For the DQP
        # convention used here, -A_parallel is the dephasing coefficient.
        return self.minus_A_par_kHz / 1000.0


@dataclass
class QECCode:
    g_MHz: tuple[float, float]
    recovery_kraus: tuple[np.ndarray, np.ndarray]
    encoding_unitary: np.ndarray
    decoding_unitary: np.ndarray
    zero_L: np.ndarray
    one_L: np.ndarray
    zero_E: np.ndarray
    one_E: np.ndarray


# -----------------------------------------------------------------------------
# Linear algebra helpers
# -----------------------------------------------------------------------------


def ket(dim: int, i: int) -> np.ndarray:
    v = np.zeros(dim, dtype=complex)
    v[i] = 1.0
    return v


def transition(dim: int, final: int, initial: int) -> np.ndarray:
    return np.outer(ket(dim, final), ket(dim, initial).conj())


def density(psi: np.ndarray) -> np.ndarray:
    return np.outer(psi, psi.conj())


def vec(rho: np.ndarray) -> np.ndarray:
    return np.asarray(rho).reshape(-1, order="F")


def mat(v: np.ndarray, dim: int) -> np.ndarray:
    return np.asarray(v).reshape((dim, dim), order="F")


def hermitize(rho: np.ndarray) -> np.ndarray:
    return 0.5 * (rho + rho.conj().T)


def partial_trace_electron(rho: np.ndarray, de: int, dn: int) -> np.ndarray:
    return np.trace(rho.reshape(de, dn, de, dn), axis1=0, axis2=2)


def bell_state_psi_plus() -> np.ndarray:
    up, down = ket(2, 0), ket(2, 1)
    return (np.kron(up, down) + np.kron(down, up)) / np.sqrt(2)


def bell_fidelity(rho_n: np.ndarray, bell: np.ndarray | None = None) -> float:
    bell = bell_state_psi_plus() if bell is None else bell
    fid = np.real(bell.conj() @ rho_n @ bell)
    return float(np.clip(fid, -1e-12, 1.0 + 1e-12))


# -----------------------------------------------------------------------------
# Lindblad model
# -----------------------------------------------------------------------------


def lindblad_liouvillian(H: np.ndarray, collapse_ops: list[np.ndarray]) -> sp.csr_matrix:
    """Return L such that d vec(rho)/dt = L vec(rho), using column stacking."""

    Hs = sp.csr_matrix(H)
    d = Hs.shape[0]
    I = sp.identity(d, format="csr", dtype=complex)
    L = -1j * (sp.kron(I, Hs, format="csr") - sp.kron(Hs.T, I, format="csr"))

    for C in collapse_ops:
        Cs = sp.csr_matrix(C)
        CdC = Cs.getH() @ Cs
        L += sp.kron(Cs.conjugate(), Cs, format="csr")
        L += -0.5 * sp.kron(I, CdC, format="csr")
        L += -0.5 * sp.kron(CdC.T, I, format="csr")
    return L.tocsr()


def evolve_liouvillian(L: sp.csr_matrix, rho0: np.ndarray, tlist_us: np.ndarray) -> np.ndarray:
    """Evolve rho0 under a time-independent Liouvillian on a uniform grid."""

    tlist_us = np.asarray(tlist_us, dtype=float)
    dt = np.diff(tlist_us)
    if len(tlist_us) < 2 or not np.allclose(dt, dt[0], rtol=1e-12, atol=1e-15):
        raise ValueError("tlist_us must be a uniform grid with at least two points")

    return spla.expm_multiply(
        L,
        vec(rho0),
        start=float(tlist_us[0]),
        stop=float(tlist_us[-1]),
        num=len(tlist_us),
        endpoint=True,
    )


_DENSE_PROPAGATOR_CACHE: dict[tuple[int, float], np.ndarray] = {}


def propagate_density(L: sp.csr_matrix, rho: np.ndarray, dt_us: float, dim: int) -> np.ndarray:
    """Propagate one density matrix by dt_us.

    The same time step is used many times when plotting between recovery
    operations, so cache the dense exp(L dt) propagator after the first call.
    This keeps realistic-cadence plots fast while preserving the same
    time-independent Lindblad dynamics.
    """

    dt = float(dt_us)
    if abs(dt) < 1e-15:
        return hermitize(rho)
    key = (id(L), round(dt, 15))
    U = _DENSE_PROPAGATOR_CACHE.get(key)
    if U is None:
        U = la.expm((L * dt).toarray())
        _DENSE_PROPAGATOR_CACHE[key] = U
    return hermitize(mat(U @ vec(rho), dim))


def make_nv_two_c13_model(
    B_T: float = 0.05,
    A_par_MHz: tuple[float, float] = (-0.2242991967686721, -0.05010705093918639),
    A_perp_MHz: tuple[float, float] = (0.19907207268788648, 0.1087263051655999),
    W_pump_per_us: float = 5.0,
    T_e0_us: float = 0.013,
    T_e1_us: float = 0.007,
    p_isc0: float = 0.14,
    p_isc1: float = 0.55,
    tau_s_us: float = 0.180,
    beta_s_to_g0: float = 0.85,
    interaction_picture: bool = True,
) -> tuple[np.ndarray, list[np.ndarray], dict, tuple[int, int]]:
    """Build the five-electron-level x two-nuclear-spin Lindblad model."""

    de, dn = 5, 4
    g0, g1, e0, e1, singlet = range(5)
    I2, In = np.eye(2, dtype=complex), np.eye(dn, dtype=complex)
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sz = np.array([[1, 0], [0, -1]], dtype=complex)
    Ix = (np.kron(sx / 2, I2), np.kron(I2, sx / 2))
    Iz = (np.kron(sz / 2, I2), np.kron(I2, sz / 2))

    gamma_13C_MHz_per_T = 10.705
    omega_L = 2 * np.pi * gamma_13C_MHz_per_T * B_T
    A_par = tuple(2 * np.pi * np.asarray(A_par_MHz, dtype=float))
    A_perp = tuple(2 * np.pi * np.asarray(A_perp_MHz, dtype=float))

    H_g0_lab = omega_L * (Iz[0] + Iz[1])
    H_g1_lab = sum((omega_L - A_par[j]) * Iz[j] + A_perp[j] * Ix[j] for j in range(2))

    if interaction_picture:
        Z = np.zeros((dn, dn), dtype=complex)
        H_g0, H_g1, H_e, H_s = Z, H_g1_lab - H_g0_lab, Z, Z
    else:
        H_g0, H_g1, H_e, H_s = H_g0_lab, H_g1_lab, H_g0_lab.copy(), H_g0_lab.copy()

    H = np.zeros((de * dn, de * dn), dtype=complex)
    for electron_index, Hn in [(g0, H_g0), (g1, H_g1), (e0, H_e), (e1, H_e), (singlet, H_s)]:
        H += np.kron(transition(de, electron_index, electron_index), Hn)

    total_e0 = 1.0 / T_e0_us
    total_e1 = 1.0 / T_e1_us
    rates = {
        "W_pump_per_us": W_pump_per_us,
        "gamma0_rad_per_us": (1.0 - p_isc0) * total_e0,
        "gamma1_rad_per_us": (1.0 - p_isc1) * total_e1,
        "kappa0_isc_per_us": p_isc0 * total_e0,
        "kappa1_isc_per_us": p_isc1 * total_e1,
        "Gamma_s_to_g0_per_us": beta_s_to_g0 / tau_s_us,
        "Gamma_s_to_g1_per_us": (1.0 - beta_s_to_g0) / tau_s_us,
        "omega_L_MHz": omega_L / (2 * np.pi),
    }

    def C(rate: float, final: int, initial: int) -> np.ndarray:
        return np.sqrt(rate) * np.kron(transition(de, final, initial), In)

    collapse_ops = [
        C(rates["W_pump_per_us"], e0, g0),
        C(rates["W_pump_per_us"], e1, g1),
        C(rates["gamma0_rad_per_us"], g0, e0),
        C(rates["gamma1_rad_per_us"], g1, e1),
        C(rates["kappa0_isc_per_us"], singlet, e0),
        C(rates["kappa1_isc_per_us"], singlet, e1),
        C(rates["Gamma_s_to_g0_per_us"], g0, singlet),
        C(rates["Gamma_s_to_g1_per_us"], g1, singlet),
    ]
    return H, collapse_ops, rates, (de, dn)


# -----------------------------------------------------------------------------
# DQP spin selection and n=2 efficient code
# -----------------------------------------------------------------------------


def load_dqp_spins(path: str | Path | None) -> list[DQPSpin]:
    if path is None or not Path(path).exists():
        raw = DEFAULT_DQP_SPINS
    else:
        # Allow a trailing comma in the JSON-like file.
        text = re.sub(r",\s*([\]\}])", r"\1", Path(path).read_text())
        raw = json.loads(text)
    return [DQPSpin(i, float(pair[0]), float(pair[1])) for i, pair in enumerate(raw, start=1)]


def choose_two_spins(
    spins: list[DQPSpin],
    strategy: str = "strongest",
    spin_indices: tuple[int, int] | None = None,
) -> list[DQPSpin]:
    if spin_indices is not None:
        by_index = {s.index: s for s in spins}
        missing = [idx for idx in spin_indices if idx not in by_index]
        if missing:
            raise ValueError(f"Unknown DQP spin indices: {missing}")
        selected = [by_index[i] for i in spin_indices]
    elif strategy == "strongest":
        selected = sorted(spins, key=lambda s: abs(s.minus_A_par_kHz), reverse=True)[:2]
    elif strategy == "closest-positive":
        pairs = []
        for i, a in enumerate(spins):
            for b in spins[i + 1 :]:
                if a.minus_A_par_kHz > 0 and b.minus_A_par_kHz > 0:
                    mismatch = abs(a.minus_A_par_kHz - b.minus_A_par_kHz) / max(
                        abs(a.minus_A_par_kHz), abs(b.minus_A_par_kHz)
                    )
                    strength = 0.5 * (abs(a.minus_A_par_kHz) + abs(b.minus_A_par_kHz))
                    pairs.append((mismatch, -strength, a, b))
        if not pairs:
            raise ValueError("No positive same-sign DQP spin pair found")
        _, _, a, b = min(pairs, key=lambda row: (row[0], row[1]))
        selected = [a, b]
    else:
        raise ValueError(f"Unknown spin-selection strategy: {strategy}")

    return sorted(selected, key=lambda s: abs(s.minus_A_par_kHz), reverse=True)


def make_two_qubit_qec_code(g_MHz: tuple[float, float]) -> QECCode:
    """Build the n=2 hardware-efficient CFD code and recovery channel.

    The code assumes |g1| >= |g2|, as in the paper.  A global sign flip of both
    couplings only relabels logical phases, so the construction normalizes g1 > 0.
    """

    g = np.asarray(g_MHz, dtype=float)
    if abs(g[0]) < abs(g[1]) - 1e-15:
        raise ValueError("Order spins so |g1| >= |g2|")
    if g[0] < 0:
        g = -g
    g1, g2 = float(g[0]), float(g[1])
    if g1 <= 0 or g1 + g2 < -1e-14 or g1 - g2 < -1e-14:
        raise ValueError("The n=2 construction requires g1 > 0 and |g2| <= g1 after sign normalization")

    # Eq. (9) normalized: a^2=(g1-g2)/(2g1), b^2=(g1+g2)/(2g1).
    a = math.sqrt(max(0.0, (g1 - g2) / (2 * g1)))
    b = math.sqrt(max(0.0, (g1 + g2) / (2 * g1)))

    # Convenient phase choice making chi0 and chi1 orthogonal and giving a
    # separable syndrome operator S = U_z \otimes Z_2.
    chi0 = np.array([a, b], dtype=complex)
    chi1 = np.array([-b, a], dtype=complex)
    zero, one = ket(2, 0), ket(2, 1)

    zero_L = np.kron(chi0, zero)
    one_L = np.kron(chi1, one)
    zero_E = np.kron(chi1, zero)
    one_E = np.kron(chi0, one)

    P_L = density(zero_L) + density(one_L)
    P_E = density(zero_E) + density(one_E)
    U_x = np.outer(chi0, chi1.conj()) + np.outer(chi1, chi0.conj())

    # Transpose/standard recovery for the n=2 case:
    # no-error syndrome leaves C0 fixed; error syndrome maps C1 back to C0.
    K_no_error = P_L
    K_error = np.kron(U_x, np.eye(2, dtype=complex)) @ P_E

    # Encoding maps computational |01> and |10> to |0_L> and |1_L>.
    # This makes U_enc |Psi+> = (|0_L> + |1_L>)/sqrt(2).
    U_enc = np.column_stack([zero_E, zero_L, one_L, one_E])
    return QECCode((g1, g2), (K_no_error, K_error), U_enc, U_enc.conj().T, zero_L, one_L, zero_E, one_E)


def model_params_from_spins(spins: list[DQPSpin], B_T: float, pump_rate: float) -> dict:
    return {
        "B_T": B_T,
        "A_par_MHz": tuple(s.A_par_MHz for s in spins),
        "A_perp_MHz": tuple(s.A_perp_MHz for s in spins),
        "W_pump_per_us": pump_rate,
        "interaction_picture": True,
    }


# -----------------------------------------------------------------------------
# QEC evolution modes
# -----------------------------------------------------------------------------


def apply_recovery_to_full_state(rho: np.ndarray, code: QECCode, de: int) -> np.ndarray:
    out = np.zeros_like(rho)
    I_e = np.eye(de, dtype=complex)
    for K_n in code.recovery_kraus:
        K = np.kron(I_e, K_n)
        out += K @ rho @ K.conj().T
    return hermitize(out)


def decoded_bell_fidelity(rho: np.ndarray, code: QECCode, de: int, dn: int) -> float:
    rho_n = partial_trace_electron(rho, de, dn)
    rho_decoded = code.decoding_unitary @ rho_n @ code.decoding_unitary.conj().T
    return bell_fidelity(rho_decoded)


def _base_no_protocol_curve(L: sp.csr_matrix, tlist_us: np.ndarray, de: int, dn: int) -> np.ndarray:
    d = de * dn
    e0, bell = ket(de, 0), bell_state_psi_plus()
    rho0 = density(np.kron(e0, bell))
    raw_vecs = evolve_liouvillian(L, rho0, tlist_us)
    return np.array([
        bell_fidelity(partial_trace_electron(hermitize(mat(v, d)), de, dn), bell)
        for v in raw_vecs
    ])


def _evolve_density_to_local_times(
    L: sp.csr_matrix,
    rho_start: np.ndarray,
    local_times_us: np.ndarray,
    dim: int,
) -> list[np.ndarray]:
    """Return rho(local_t) for each local_t, all evolved from the same rho_start."""

    local_times_us = np.asarray(local_times_us, dtype=float)
    if len(local_times_us) == 0:
        return []
    if np.any(local_times_us < -1e-12):
        raise ValueError("local_times_us must be nonnegative")
    if len(local_times_us) == 1:
        return [propagate_density(L, rho_start, float(local_times_us[0]), dim)]

    # expm_multiply can generate a whole uniform segment in one Krylov run.
    dt = np.diff(local_times_us)
    if np.allclose(dt, dt[0], rtol=1e-10, atol=1e-12):
        vecs = spla.expm_multiply(
            L,
            vec(rho_start),
            start=float(local_times_us[0]),
            stop=float(local_times_us[-1]),
            num=len(local_times_us),
            endpoint=True,
        )
        return [hermitize(mat(v, dim)) for v in vecs]

    # Fallback for an arbitrary grid.  This path is rarely used for the default
    # settings because recovery times are aligned to the plot grid.
    return [propagate_density(L, rho_start, float(t), dim) for t in local_times_us]


def _store_state_arrays(
    states: list[np.ndarray],
    indices: np.ndarray,
    f_with: np.ndarray,
    tr_with: np.ndarray,
    recovery_count: np.ndarray,
    code: QECCode,
    de: int,
    dn: int,
    count: int,
) -> None:
    for idx, rho_t in zip(indices, states):
        f_with[idx] = decoded_bell_fidelity(rho_t, code, de, dn)
        tr_with[idx] = float(np.real(np.trace(rho_t)))
        recovery_count[idx] = count


def simulate_periodic_recovery(
    tlist_us: np.ndarray,
    model_params: dict,
    code: QECCode,
    recovery_interval_us: float,
) -> dict:
    """Evolution with ideal QEC recovery applied every recovery_interval_us."""

    tlist_us = np.asarray(tlist_us, dtype=float)
    if recovery_interval_us <= 0:
        raise ValueError("recovery_interval_us must be positive")
    if abs(tlist_us[0]) > 1e-15:
        raise ValueError("tlist_us must start at 0")

    H, C, rates, (de, dn) = make_nv_two_c13_model(**model_params)
    L = lindblad_liouvillian(H, C)
    d = de * dn
    f_without = _base_no_protocol_curve(L, tlist_us, de, dn)

    e0, bell = ket(de, 0), bell_state_psi_plus()
    rho_start = density(np.kron(e0, code.encoding_unitary @ bell))
    f_with = np.zeros(len(tlist_us))
    tr_with = np.zeros(len(tlist_us))
    recovery_count = np.zeros(len(tlist_us), dtype=int)

    # t=0 value, before any recovery.
    f_with[0] = decoded_bell_fidelity(rho_start, code, de, dn)
    tr_with[0] = float(np.real(np.trace(rho_start)))

    t_end = float(tlist_us[-1])
    seg_start = 0.0
    count = 0
    tol = 1e-12

    while seg_start < t_end - tol:
        seg_end = min(seg_start + recovery_interval_us, t_end)
        output_indices = np.where((tlist_us > seg_start + tol) & (tlist_us <= seg_end + tol))[0]
        output_times = tlist_us[output_indices]

        need_recovery = seg_end < t_end + tol and abs(seg_end - (seg_start + recovery_interval_us)) <= 1e-9
        seg_end_is_output = len(output_times) > 0 and abs(output_times[-1] - seg_end) <= 1e-9

        # Propagate to all output times in this segment, and also to seg_end if
        # a recovery is needed there but seg_end is not on the output grid.
        eval_times = list(output_times)
        if need_recovery and not seg_end_is_output:
            eval_times.append(seg_end)
        eval_times = np.array(eval_times, dtype=float)
        local_times = eval_times - seg_start
        states = _evolve_density_to_local_times(L, rho_start, local_times, d) if len(eval_times) else []

        # Map eval states back to output states before the recovery at seg_end.
        state_by_time = {round(float(t), 12): rho for t, rho in zip(eval_times, states)}
        pre_recovery_output_indices = output_indices
        pre_recovery_states = [state_by_time[round(float(t), 12)] for t in output_times]
        _store_state_arrays(pre_recovery_states, pre_recovery_output_indices, f_with, tr_with, recovery_count, code, de, dn, count)

        # Apply recovery at the segment end and overwrite the boundary output
        # point with the post-recovery fidelity when seg_end is sampled.
        if need_recovery:
            rho_end = state_by_time.get(round(float(seg_end), 12))
            if rho_end is None:
                rho_end = propagate_density(L, rho_start, seg_end - seg_start, d)
            rho_start = apply_recovery_to_full_state(rho_end, code, de)
            count += 1
            boundary_matches = np.where(np.abs(tlist_us - seg_end) <= 1e-9)[0]
            if len(boundary_matches):
                idx = int(boundary_matches[0])
                f_with[idx] = decoded_bell_fidelity(rho_start, code, de, dn)
                tr_with[idx] = float(np.real(np.trace(rho_start)))
                recovery_count[idx] = count
        else:
            rho_start = states[-1] if states else rho_start

        seg_start = seg_end

    return {
        "mode": "periodic",
        "t_us": tlist_us,
        "fidelity_without_protocol": f_without,
        "fidelity_with_protocol": f_with,
        "trace_with_protocol": tr_with,
        "recovery_count": recovery_count,
        "recovery_interval_us": float(recovery_interval_us),
        "single_recovery_time_us": None,
        "rates": rates,
    }


def simulate_single_recovery_trace(
    tlist_us: np.ndarray,
    model_params: dict,
    code: QECCode,
    single_recovery_time_us: float,
) -> dict:
    """Evolution with exactly one ideal QEC recovery at single_recovery_time_us."""

    tlist_us = np.asarray(tlist_us, dtype=float)
    if single_recovery_time_us <= 0 or single_recovery_time_us > tlist_us[-1] + 1e-12:
        raise ValueError("single_recovery_time_us must lie inside the plotted time window")
    if abs(tlist_us[0]) > 1e-15:
        raise ValueError("tlist_us must start at 0")

    H, C, rates, (de, dn) = make_nv_two_c13_model(**model_params)
    L = lindblad_liouvillian(H, C)
    d = de * dn
    f_without = _base_no_protocol_curve(L, tlist_us, de, dn)

    e0, bell = ket(de, 0), bell_state_psi_plus()
    rho0 = density(np.kron(e0, code.encoding_unitary @ bell))
    f_with = np.zeros(len(tlist_us))
    tr_with = np.zeros(len(tlist_us))
    recovery_count = np.zeros(len(tlist_us), dtype=int)

    tol = 1e-12
    f_with[0] = decoded_bell_fidelity(rho0, code, de, dn)
    tr_with[0] = float(np.real(np.trace(rho0)))

    # Segment before and including the recovery time.
    before_indices = np.where((tlist_us > 0.0 + tol) & (tlist_us <= single_recovery_time_us + tol))[0]
    before_times = tlist_us[before_indices]
    recovery_is_output = len(before_times) > 0 and abs(before_times[-1] - single_recovery_time_us) <= 1e-9
    eval_times = list(before_times)
    if not recovery_is_output:
        eval_times.append(single_recovery_time_us)
    eval_times = np.array(eval_times, dtype=float)
    before_states = _evolve_density_to_local_times(L, rho0, eval_times, d) if len(eval_times) else []
    state_by_time = {round(float(t), 12): rho for t, rho in zip(eval_times, before_states)}

    before_output_states = [state_by_time[round(float(t), 12)] for t in before_times]
    _store_state_arrays(before_output_states, before_indices, f_with, tr_with, recovery_count, code, de, dn, 0)

    rho_at_recovery = state_by_time.get(round(float(single_recovery_time_us), 12))
    if rho_at_recovery is None:
        rho_at_recovery = propagate_density(L, rho0, single_recovery_time_us, d)
    rho_after_recovery = apply_recovery_to_full_state(rho_at_recovery, code, de)

    # If the recovery time is sampled, overwrite it with the post-recovery value.
    boundary_matches = np.where(np.abs(tlist_us - single_recovery_time_us) <= 1e-9)[0]
    if len(boundary_matches):
        idx = int(boundary_matches[0])
        f_with[idx] = decoded_bell_fidelity(rho_after_recovery, code, de, dn)
        tr_with[idx] = float(np.real(np.trace(rho_after_recovery)))
        recovery_count[idx] = 1

    # Segment after the recovery.
    after_indices = np.where(tlist_us > single_recovery_time_us + tol)[0]
    after_times = tlist_us[after_indices]
    local_after = after_times - single_recovery_time_us
    after_states = _evolve_density_to_local_times(L, rho_after_recovery, local_after, d) if len(after_times) else []
    _store_state_arrays(after_states, after_indices, f_with, tr_with, recovery_count, code, de, dn, 1)

    return {
        "mode": "single",
        "t_us": tlist_us,
        "fidelity_without_protocol": f_without,
        "fidelity_with_protocol": f_with,
        "trace_with_protocol": tr_with,
        "recovery_count": recovery_count,
        "recovery_interval_us": None,
        "single_recovery_time_us": float(single_recovery_time_us),
        "rates": rates,
    }


# -----------------------------------------------------------------------------
# Output utilities
# -----------------------------------------------------------------------------


def save_csv(result: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "t_us",
            "bell_fidelity_without_protocol",
            "decoded_bell_fidelity_with_qec",
            "recovery_count_applied",
        ])
        for row in zip(
            result["t_us"],
            result["fidelity_without_protocol"],
            result["fidelity_with_protocol"],
            result["recovery_count"],
        ):
            w.writerow([f"{row[0]:.12g}", f"{row[1]:.12g}", f"{row[2]:.12g}", int(row[3])])


def _spin_text(selected: list[DQPSpin]) -> str:
    return ", ".join(
        f"#{s.index}: -A_par={s.minus_A_par_kHz:.3g} kHz, A_perp={s.A_perp_kHz:.3g} kHz" for s in selected
    )


def plot_overlay(result: dict, selected: list[DQPSpin], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig = plt.figure(figsize=(7.4, 4.8))
    ax = fig.add_subplot(111)
    ax.plot(result["t_us"], result["fidelity_without_protocol"], label=r"Without protocol: physical $|\Psi^+\rangle$")

    if result["mode"] == "periodic":
        label = f"With QEC: ideal recovery every {result['recovery_interval_us']:.3g} µs"
        title = "Bell-state fidelity with realistic-cadence QEC recovery"
        box_line = f"recovery interval = {result['recovery_interval_us']:.3g} µs"
    elif result["mode"] == "single":
        label = "With QEC: exactly one ideal recovery"
        title = "Bell-state fidelity with one QEC recovery operation"
        box_line = f"single recovery at t = {result['single_recovery_time_us']:.3g} µs"
        ax.axvline(result["single_recovery_time_us"], linestyle="--", linewidth=1.0, label="single recovery time")
    else:
        label = "With QEC protocol"
        title = "Two-13C Bell-state fidelity with common-fluctuator QEC"
        box_line = ""

    ax.plot(result["t_us"], result["fidelity_with_protocol"], label=label)
    ax.set_xlabel("Time (µs)")
    ax.set_ylabel("Bell-state fidelity")
    ax.set_title(title)
    ax.set_ylim(0.0, 1.02)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")
    ax.text(
        0.02,
        0.04,
        f"DQP spins {_spin_text(selected)}\n{box_line}\nideal instantaneous recovery channel; gate errors not included",
        transform=ax.transAxes,
        fontsize=8.2,
        va="bottom",
        bbox={"boxstyle": "round", "alpha": 0.12},
    )
    fig.tight_layout()
    fig.savefig(path, dpi=220)
    plt.close(fig)


def run_sanity_checks(code: QECCode, results: list[dict]) -> None:
    basis = np.column_stack([code.zero_L, code.one_L, code.zero_E, code.one_E])
    orth_err = float(np.max(np.abs(basis.conj().T @ basis - np.eye(4))))
    cptp_err = float(np.max(np.abs(sum(K.conj().T @ K for K in code.recovery_kraus) - np.eye(4))))
    trace_err = max(float(np.max(np.abs(r["trace_with_protocol"] - 1.0))) for r in results)
    fid_low = min(float(np.min(r["fidelity_with_protocol"])) for r in results)
    fid_high = max(float(np.max(r["fidelity_with_protocol"])) for r in results)
    if orth_err > 1e-12 or cptp_err > 1e-12 or trace_err > 1e-8 or fid_low < -1e-8 or fid_high > 1.0 + 1e-8:
        raise RuntimeError(
            "Sanity check failed: "
            f"orth={orth_err:.3e}, cptp={cptp_err:.3e}, trace={trace_err:.3e}, "
            f"fid_range=({fid_low:.3e}, {fid_high:.3e})"
        )


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dqp-file", default="dqpspins.json")
    p.add_argument("--selection", choices=["strongest", "closest-positive"], default="strongest")
    p.add_argument("--spin-indices", nargs=2, type=int, metavar=("I", "J"), help="1-based DQP spin indices")
    p.add_argument("--time-us", type=float, default=20.0)
    p.add_argument("--plot-dt-us", type=float, default=0.5, help="time spacing used only for plotting/data output")
    p.add_argument(
        "--recovery-interval-us",
        type=float,
        default=10.0,
        help="periodic QEC recovery cadence in microseconds; default is a less idealized 10 us",
    )
    p.add_argument(
        "--single-recovery-time-us",
        type=float,
        default=None,
        help="time of the one-and-only recovery operation; default is half of --time-us",
    )
    p.add_argument("--B-T", type=float, default=0.05)
    p.add_argument("--pump-rate", type=float, default=5.0)
    p.add_argument("--output-dir", default="outputs")
    p.add_argument("--skip-checks", action="store_true")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    if args.time_us <= 0 or args.plot_dt_us <= 0:
        raise ValueError("--time-us and --plot-dt-us must be positive")

    spins = load_dqp_spins(args.dqp_file)
    selected = choose_two_spins(spins, args.selection, tuple(args.spin_indices) if args.spin_indices else None)
    params = model_params_from_spins(selected, args.B_T, args.pump_rate)
    code = make_two_qubit_qec_code(tuple(s.g_MHz for s in selected))

    tlist = np.arange(0.0, args.time_us + 0.5 * args.plot_dt_us, args.plot_dt_us)
    single_time = args.single_recovery_time_us if args.single_recovery_time_us is not None else 0.5 * args.time_us

    periodic = simulate_periodic_recovery(tlist, params, code, args.recovery_interval_us)
    single = simulate_single_recovery_trace(tlist, params, code, single_time)
    if not args.skip_checks:
        run_sanity_checks(code, [periodic, single])

    out = Path(args.output_dir)
    periodic_png = out / "qec_bell_fidelity_periodic_realistic_interval.png"
    periodic_svg = out / "qec_bell_fidelity_periodic_realistic_interval.svg"
    periodic_csv = out / "qec_bell_fidelity_periodic_realistic_interval.csv"
    single_png = out / "qec_bell_fidelity_single_recovery.png"
    single_svg = out / "qec_bell_fidelity_single_recovery.svg"
    single_csv = out / "qec_bell_fidelity_single_recovery.csv"

    plot_overlay(periodic, selected, periodic_png)
    plot_overlay(periodic, selected, periodic_svg)
    save_csv(periodic, periodic_csv)
    plot_overlay(single, selected, single_png)
    plot_overlay(single, selected, single_svg)
    save_csv(single, single_csv)

    print("Simulation completed.")
    print("Selected DQP spins, ordered as |g1| >= |g2|:")
    for s in selected:
        print(
            f"  spin #{s.index}: -A_parallel={s.minus_A_par_kHz:.9g} kHz, "
            f"A_parallel={-s.minus_A_par_kHz:.9g} kHz, A_perp={s.A_perp_kHz:.9g} kHz"
        )
    print(f"QEC couplings: g1={code.g_MHz[0]:.9g} MHz, g2={code.g_MHz[1]:.9g} MHz")
    print(f"Plot dt: {args.plot_dt_us:.9g} us")
    print(f"Periodic recovery interval: {periodic['recovery_interval_us']:.9g} us")
    print(f"Single recovery time: {single['single_recovery_time_us']:.9g} us")
    print("Final Bell-state fidelities at t = {:.9g} us:".format(tlist[-1]))
    print(f"  without protocol                         : {periodic['fidelity_without_protocol'][-1]:.6f}")
    print(f"  periodic QEC, decoded                    : {periodic['fidelity_with_protocol'][-1]:.6f}")
    print(f"  periodic improvement                     : {periodic['fidelity_with_protocol'][-1] - periodic['fidelity_without_protocol'][-1]:+.6f}")
    print(f"  single-recovery QEC trace, decoded       : {single['fidelity_with_protocol'][-1]:.6f}")
    print(f"  single-recovery improvement              : {single['fidelity_with_protocol'][-1] - single['fidelity_without_protocol'][-1]:+.6f}")
    print("Saved:")
    for path in [periodic_png, periodic_svg, periodic_csv, single_png, single_svg, single_csv]:
        print(f"  {path}")


if __name__ == "__main__":
    main()
